
package studentmanagement;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "StudentManagementImplService", targetNamespace = "http://StudentManagement/", wsdlLocation = "http://localhost:8080/StudentService/?wsdl")
public class StudentManagementImplService
    extends Service
{

    private final static URL STUDENTMANAGEMENTIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException STUDENTMANAGEMENTIMPLSERVICE_EXCEPTION;
    private final static QName STUDENTMANAGEMENTIMPLSERVICE_QNAME = new QName("http://StudentManagement/", "StudentManagementImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/StudentService/?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        STUDENTMANAGEMENTIMPLSERVICE_WSDL_LOCATION = url;
        STUDENTMANAGEMENTIMPLSERVICE_EXCEPTION = e;
    }

    public StudentManagementImplService() {
        super(__getWsdlLocation(), STUDENTMANAGEMENTIMPLSERVICE_QNAME);
    }

    public StudentManagementImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), STUDENTMANAGEMENTIMPLSERVICE_QNAME, features);
    }

    public StudentManagementImplService(URL wsdlLocation) {
        super(wsdlLocation, STUDENTMANAGEMENTIMPLSERVICE_QNAME);
    }

    public StudentManagementImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, STUDENTMANAGEMENTIMPLSERVICE_QNAME, features);
    }

    public StudentManagementImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public StudentManagementImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns StudentManagement
     */
    @WebEndpoint(name = "StudentManagementImplPort")
    public StudentManagement getStudentManagementImplPort() {
        return super.getPort(new QName("http://StudentManagement/", "StudentManagementImplPort"), StudentManagement.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns StudentManagement
     */
    @WebEndpoint(name = "StudentManagementImplPort")
    public StudentManagement getStudentManagementImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://StudentManagement/", "StudentManagementImplPort"), StudentManagement.class, features);
    }

    private static URL __getWsdlLocation() {
        if (STUDENTMANAGEMENTIMPLSERVICE_EXCEPTION!= null) {
            throw STUDENTMANAGEMENTIMPLSERVICE_EXCEPTION;
        }
        return STUDENTMANAGEMENTIMPLSERVICE_WSDL_LOCATION;
    }

}
