
package academicstaffmanagement;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "AcademicStaffManagement", targetNamespace = "http://AcademicStaffManagement/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface AcademicStaffManagement {


    /**
     * 
     * @param academicStaffRegistration
     * @return
     *     returns boolean
     * @throws JAXBException_Exception
     * @throws FileNotFoundException_Exception
     */
    @WebMethod
    @WebResult(name = "isRegistered", partName = "isRegistered")
    @Action(input = "http://AcademicStaffManagement/AcademicStaffManagement/isRegisteredRequest", output = "http://AcademicStaffManagement/AcademicStaffManagement/isRegisteredResponse", fault = {
        @FaultAction(className = FileNotFoundException_Exception.class, value = "http://AcademicStaffManagement/AcademicStaffManagement/isRegistered/Fault/FileNotFoundException"),
        @FaultAction(className = JAXBException_Exception.class, value = "http://AcademicStaffManagement/AcademicStaffManagement/isRegistered/Fault/JAXBException")
    })
    public boolean isRegistered(
        @WebParam(name = "academicStaffRegistration", partName = "academicStaffRegistration")
        AcademicStaff academicStaffRegistration)
        throws FileNotFoundException_Exception, JAXBException_Exception
    ;

    /**
     * 
     * @param registerAcademicStaff
     * @throws JAXBException_Exception
     * @throws FileNotFoundException_Exception
     */
    @WebMethod
    @Action(input = "http://AcademicStaffManagement/AcademicStaffManagement/registerUserRequest", output = "http://AcademicStaffManagement/AcademicStaffManagement/registerUserResponse", fault = {
        @FaultAction(className = FileNotFoundException_Exception.class, value = "http://AcademicStaffManagement/AcademicStaffManagement/registerUser/Fault/FileNotFoundException"),
        @FaultAction(className = JAXBException_Exception.class, value = "http://AcademicStaffManagement/AcademicStaffManagement/registerUser/Fault/JAXBException")
    })
    public void registerUser(
        @WebParam(name = "registerAcademicStaff", partName = "registerAcademicStaff")
        AcademicStaff registerAcademicStaff)
        throws FileNotFoundException_Exception, JAXBException_Exception
    ;

    /**
     * 
     * @param module
     * @param assigningModule
     * @return
     *     returns boolean
     * @throws JAXBException_Exception
     * @throws FileNotFoundException_Exception
     */
    @WebMethod
    @WebResult(name = "assignModule", partName = "assignModule")
    @Action(input = "http://AcademicStaffManagement/AcademicStaffManagement/assignModuleRequest", output = "http://AcademicStaffManagement/AcademicStaffManagement/assignModuleResponse", fault = {
        @FaultAction(className = FileNotFoundException_Exception.class, value = "http://AcademicStaffManagement/AcademicStaffManagement/assignModule/Fault/FileNotFoundException"),
        @FaultAction(className = JAXBException_Exception.class, value = "http://AcademicStaffManagement/AcademicStaffManagement/assignModule/Fault/JAXBException")
    })
    public boolean assignModule(
        @WebParam(name = "assigningModule", partName = "assigningModule")
        AcademicStaff assigningModule,
        @WebParam(name = "module", partName = "module")
        AcStaffModule module)
        throws FileNotFoundException_Exception, JAXBException_Exception
    ;

    /**
     * 
     * @param getUserAcademicStaff
     * @return
     *     returns academicstaffmanagement.AcademicStaff
     * @throws JAXBException_Exception
     * @throws FileNotFoundException_Exception
     */
    @WebMethod
    @WebResult(name = "getUser", partName = "getUser")
    @Action(input = "http://AcademicStaffManagement/AcademicStaffManagement/getUserRequest", output = "http://AcademicStaffManagement/AcademicStaffManagement/getUserResponse", fault = {
        @FaultAction(className = FileNotFoundException_Exception.class, value = "http://AcademicStaffManagement/AcademicStaffManagement/getUser/Fault/FileNotFoundException"),
        @FaultAction(className = JAXBException_Exception.class, value = "http://AcademicStaffManagement/AcademicStaffManagement/getUser/Fault/JAXBException")
    })
    public AcademicStaff getUser(
        @WebParam(name = "getUserAcademicStaff", partName = "getUserAcademicStaff")
        int getUserAcademicStaff)
        throws FileNotFoundException_Exception, JAXBException_Exception
    ;

}
