
package academicstaffmanagement;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "AcademicStaffManagmentImplService", targetNamespace = "http://AcademicStaffManagement/", wsdlLocation = "http://localhost:8080/AcademicStaffService/?wsdl")
public class AcademicStaffManagmentImplService
    extends Service
{

    private final static URL ACADEMICSTAFFMANAGMENTIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException ACADEMICSTAFFMANAGMENTIMPLSERVICE_EXCEPTION;
    private final static QName ACADEMICSTAFFMANAGMENTIMPLSERVICE_QNAME = new QName("http://AcademicStaffManagement/", "AcademicStaffManagmentImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/AcademicStaffService/?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ACADEMICSTAFFMANAGMENTIMPLSERVICE_WSDL_LOCATION = url;
        ACADEMICSTAFFMANAGMENTIMPLSERVICE_EXCEPTION = e;
    }

    public AcademicStaffManagmentImplService() {
        super(__getWsdlLocation(), ACADEMICSTAFFMANAGMENTIMPLSERVICE_QNAME);
    }

    public AcademicStaffManagmentImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ACADEMICSTAFFMANAGMENTIMPLSERVICE_QNAME, features);
    }

    public AcademicStaffManagmentImplService(URL wsdlLocation) {
        super(wsdlLocation, ACADEMICSTAFFMANAGMENTIMPLSERVICE_QNAME);
    }

    public AcademicStaffManagmentImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ACADEMICSTAFFMANAGMENTIMPLSERVICE_QNAME, features);
    }

    public AcademicStaffManagmentImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AcademicStaffManagmentImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns AcademicStaffManagement
     */
    @WebEndpoint(name = "AcademicStaffManagmentImplPort")
    public AcademicStaffManagement getAcademicStaffManagmentImplPort() {
        return super.getPort(new QName("http://AcademicStaffManagement/", "AcademicStaffManagmentImplPort"), AcademicStaffManagement.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AcademicStaffManagement
     */
    @WebEndpoint(name = "AcademicStaffManagmentImplPort")
    public AcademicStaffManagement getAcademicStaffManagmentImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://AcademicStaffManagement/", "AcademicStaffManagmentImplPort"), AcademicStaffManagement.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ACADEMICSTAFFMANAGMENTIMPLSERVICE_EXCEPTION!= null) {
            throw ACADEMICSTAFFMANAGMENTIMPLSERVICE_EXCEPTION;
        }
        return ACADEMICSTAFFMANAGMENTIMPLSERVICE_WSDL_LOCATION;
    }

}
